ronin-chain/ronin

go.mod, go.sum
The new blst version fixes this build issue with go1.24.
```
../../go/pkg/mod/github.com/supranational/blst@v0.3.11/bindings/go/blst.go:207:11: cannot define new methods on non-local type SecretKey
../../go/pkg/mod/github.com/supranational/blst@v0.3.11/bindings/go/blst.go:310:15: cannot define new methods on non-local type SecretKey
../../go/pkg/mod/github.com/supranational/blst@v0.3.11/bindings/go/blst.go:430:11: cannot define new methods on non-local type Fp12
../../go/pkg/mod/github.com/supranational/blst@v0.3.11/bindings/go/blst.go:434:11: cannot define new methods on non-local type Fp12
../../go/pkg/mod/github.com/supranational/blst@v0.3.11/bindings/go/blst.go:438:11: cannot define new methods on non-local type Fp12
../../go/pkg/mod/github.com/supranational/blst@v0.3.11/bindings/go/bl …
```
=> go.mod: bump blst to version 0.3.14

core/state_transition.go, eth/tracers/api_test.go, eth/tracers/internal/tracetest/calltrace2_test.go, eth/tracers/internal/tracetest/calltrace_test.go, eth/tracers/internal/tracetest/flat_calltrace_test.go, eth/tracers/internal/tracetest/prestate_test.go
fix for changes related to https://github.com/axieinfinity/ronin/pull/565.It will be failed when try to apply txs for tracing system transtions with error "out of gas" because the ts.gas return 0 when bypassing Precheck logic in first step.
=> core/state_transition: Avoid out of gas when tracing system txs

core/state_transition.go
System transaction is not affected by basefee rule in normal flow, the tip from system transaction is always 0. This commit makes the tracing flow consistent with this behavior.
=> core: set tip = 0 for system transaction in tracing

eth/gasprice/feehistory.go
The returned reward of system transaction is negative. This is because system transaction does not follow basefee rule. This commit fixes the issue by setting the returned reward of system transaction to 0.
=> eth/feehistory: set reward of system transaction to 0

core/state_transition.go
As the system transaction does not follow the basefee rule, make this behavior consistent in tracing path. This commit also refactors the code the skip the whole transaction's epilogue for system transaction in tracing.
=> core: don't add basefee to treasury in system transaction in tracing

consensus/consortium/common/contract.go, consensus/consortium/common/contract_test.go, core/types/transaction.go, eth/gasestimator/gasestimator.go, eth/tracers/internal/tracetest/calltrace_test.go, internal/ethapi/transaction_args.go, les/odr_test.go, light/odr_test.go, tests/state_test_util.go
core/types from https://github.com/ethereum/go-ethereum/pull/30078
=> core/types: transaction NewMessage() add authList

core/types/transaction_signing.go
Quoted from the comment in the file
"eip2930Signer and londonSigner must define Payer instead of using the same Payer defined in base MikoSigner because internally, Payer calls to Sender(signer, tx) which supports caching the recovered sender if the signer matches. So if we let the MikoSigner.Payer be called, the signer passed to Sender(signer, tx) is MikoSigner not eip2930Signer/londonSigner which unmatches with signer in cached recovered address. As a result, the sender must be recovered again which wastes CPU."
So we need to do the same for cancunSigner by defining the Payer method.
```
goos: darwin
goarch: arm64
pkg: github.com/ethereum/go-ethereum/core/txpool/legacypool cpu: Apple M1 Pro
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base …
```
=> core/types: add Payer for cancunSigner

core/blockchain_test.go, core/vm/eips.go, core/vm/evm.go, core/vm/interpreter.go, core/vm/jump_table.go, core/vm/operations_acl.go, core/vm/program/program.go, core/vm/program/program_test.go, core/vm/program/readme.md, core/vm/runtime/runtime_test.go
content:
- update core/vm
- update EXT... gas estimation
from:
- https://github.com/ethereum/go-ethereum/pull/30078
- https://github.com/ethereum/go-ethereum/pull/31089
=> core/vm: update 7702 EVM resolve code & gas estimation

common/mclock/alarm.go, common/mclock/alarm_test.go, p2p/discover/common.go, p2p/discover/lookup.go, p2p/discover/node.go, p2p/discover/table.go, p2p/discover/table_reval.go, p2p/discover/table_reval_test.go, p2p/discover/table_test.go, p2p/discover/table_util_test.go, p2p/discover/v4_lookup_test.go, p2p/discover/v4_udp.go, p2p/discover/v4_udp_test.go, p2p/discover/v5_udp.go, p2p/discover/v5_udp_test.go
Cherry-picked following commits from go-ethereum to improve table revalidation and fix some follow-after issues.
https://github.com/ethereum/go-ethereum/pull/29572
https://github.com/ethereum/go-ethereum/pull/29864
https://github.com/ethereum/go-ethereum/pull/29836
https://github.com/ethereum/go-ethereum/pull/30239
The current node discovery revalidation process in the distributed network has issues leading to inconsistent results, such as unexpected node drops (drop at the first time that revalidate failed) and uneven revalidation frequencies. The old approach involved selecting a random bucket every ~10s, validating the last node via PING, and replacing it if unresponsive. However, it was inefficient, revalidating each node every ~13.3 minutes, with uneven distribution favoring …
=> p2p/discover: improved node revalidation

accounts/abi/bind/backends/simulated.go, cmd/evm/internal/t8ntool/transaction.go, core/bench_test.go, core/blockchain_test.go, core/error.go, core/state/state_object.go, core/state/statedb.go, core/state_processor_test.go, core/state_transition.go, core/txpool/validation.go, core/vm/interface.go, eth/gasestimator/gasestimator.go, light/txpool.go, params/protocol_params.go, tests/transaction_test_util.go
content: remaining core components
from: https://github.com/ethereum/go-ethereum/pull/30078
=> core: state_transition with AuthList

consensus/consortium/v1/consortium.go, consensus/consortium/v2/consortium.go
In snapshot function, the call to snap.apply requires original parents slice, however, parents slice's length is shrinked but the underlying data is unchanged. So it is enough to create a shallow copy slice, this can help to reduce the overhead of deep copy that slice.
=> consortium: shallow copy parents slice

core/txpool/blobpool/blobpool.go, core/txpool/legacypool/legacypool.go, core/txpool/subpool.go, core/txpool/txpool.go, eth/handler.go, eth/handler_test.go, eth/protocols/eth/handler.go, eth/protocols/eth/handler_test.go, eth/protocols/eth/handlers.go
commit https://github.com/ethereum/go-ethereum/commit/930836ed66c9ff8eaffc8cd168cd9c76fad82c29.
Currently, when answering GetPooledTransaction request, txpool.Get() is used. When the requested hash is blob transaction, blobpool.Get() is called. This function loads the RLP-encoded transaction from limbo then decodes and returns. Later, in answerGetPooledTransactions, we need to RLP encode again. This decode then encode is wasteful. This commit adds GetRLP to transaction pool interface so that answerGetPooledTransactions can use the RLP-encoded from limbo directly.
Co-authored-by: Gary Rong \<garyrong0905@gmail.com\>
=> core/txpool, eth: add GetRLP to transaction pool (#31307)

accounts/abi/bind/backends/simulated.go, cmd/evm/internal/t8ntool/transaction.go, common/hexutil/json.go, common/hexutil/json_test.go, core/blockchain_test.go, core/state_processor_test.go, core/state_transition.go, core/txpool/validation.go, core/types/gen_authorization.go, core/types/setcode_tx.go, core/types/transaction.go, core/types/transaction_marshalling.go, core/types/transaction_signing.go, eth/gasestimator/gasestimator.go, eth/tracers/logger/gen_structlog.go, eth/tracers/logger/logger.go, internal/ethapi/api.go, internal/ethapi/transaction_args.go, light/txpool.go, tests/state_test_util.go, tests/transaction_test_util.go
from:
- https://github.com/ethereum/go-ethereum/pull/30926 requires a base PR https://github.com/ethereum/go-ethereum/pull/28628 to introduce a new type `hexutil.U256`
- https://github.com/ethereum/go-ethereum/pull/30933
- https://github.com/ethereum/go-ethereum/commit/73a4ecf675f6714e1fdf49904ce9426841de2e02#diff-5b2b4821bafb20115ce7d493a23dcb27dd173247f1146c2ab971cabadffc62ef
- https://github.com/ethereum/go-ethereum/pull/30936 (not related)
- https://github.com/ethereum/go-ethereum/pull/30935
=> all: refactor names & singner 7702 

cmd/ronin/main.go, cmd/utils/flags.go, p2p/server.go
This commit adds flag --trusted-node-only, when using this flag, node will only accept connection from a trusted peer. This is suboptimal as it does not change the dial logic which still tries to dial not trusted peer. But it works for now, the dial part can be in the future improvement.
=> p2p: add a flag to only accept connection from a trusted peer

cmd/ronin/main.go, cmd/utils/flags.go, core/txpool/blobpool/blobpool.go, core/txpool/blobpool/blobpool_test.go, core/txpool/blobpool/lookup.go, core/txpool/legacypool/legacypool.go, core/txpool/subpool.go, core/txpool/txpool.go, core/types/transaction.go, eth/backend.go, eth/ethconfig/config.go, eth/handler.go, eth/handler_eth.go, eth/handler_test.go, eth/protocols/eth/handler.go, eth/protocols/eth/handlers.go, p2p/enode/urlv4.go, p2p/enode/urlv4_test.go
This commit adds a flag --disable-tx-broadcast.from so that node operator can provide enode ids (e.g. --disable-tx-broadcast.from cfa5f00c55eba79f359c9d95f5c0b2bb8e173867ffbb6e212c6799a52918502519e56650970e34caf1cd17418d4da46c3243588578886c3b4f8c42d1934bf108). Transaction originated from the peer has those enode ids will not be broadcasted to any other peers.
=> eth: disable transaction broadcast based on originated peer

core/state/journal.go, core/state/state_object.go, core/state/state_test.go, core/state/statedb.go, core/state/statedb_fuzz_test.go, core/state/statedb_test.go, core/vm/evm.go, core/vm/interface.go, eth/tracers/api_test.go, internal/ethapi/api_test.go
from:
- https://github.com/ethereum/go-ethereum/pull/29520
- https://github.com/ethereum/go-ethereum/pull/30185
=> core/state: correct account selfdestruct EIP-6780 (part of 7702)

consensus/ethash/consensus.go, core/genesis.go, tests/block_test.go, tests/block_test_util.go, tests/download-fixtures.sh, tests/gen_btheader.go, tests/init.go
This PR introduces:
- Add `BlobGasUsed` and `ExcessBlobGas` to genesis and header of block in `block_test` to ensure block hash matches with generated spec-tests.
- After Paris hardfork, the block reward is set to 0 because the transition from PoW to PoS ([EIP-3675](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3675.md)). Since Ronin does not declare the `Paris` hardfork and uses a different consensus mechanism than geth, this PR uses the `Shanghai` hardfork instead to specify the consensus rule that sets the reward to 0.
```
$ go test -tags=blst_enabled,ckzg -timeout 30m -v -count=1 github.com/ethereum/go-ethereum/tests -run "TestState|TestExecutionSpecState|TestTransaction|TestRLP"
PASS
ok      github.com/ethereum/go-ethereum/tests   2.395s
```
=> all: adapt blockchain test

.github/workflows/ci-test-and-coverage.yml, core/vm/contracts.go, core/vm/instructions.go
**Reference**: https://github.com/ethereum/go-ethereum/pull/25183
This fix is related to bug reported at https://github.com/ethereum/go-ethereum/security/advisories/GHSA-69v6-xc2j-r2jf. 
Previously, the solution was deep copying the return data for all CALL opcodes before setting memory, which was redundant for precompiled contracts other than `dataCopy` (at `0x04`).
In this PR, the return data is deep copied only when the precompiled contract is dataCopy (at 0x04) to optimize performance.
=> core/vm: return copy of input slice in identity precompile, avoid return data copy

core/vote/vote_pool.go, core/vote/vote_pool_test.go
This enhances logic for `putIntoVotePool` to prevent honest peer got dropped when reached max cap of current vote per block (64)
=> core/vote: not drop peer when exceeding maximum votes per block

cmd/utils/flags.go, core/tracing/hooks.go, core/vm/evm.go, core/vm/runtime/runtime_test.go, eth/tracers/api.go, eth/tracers/dir.go, eth/tracers/internal/tracetest/calltrace2_test.go, eth/tracers/internal/tracetest/calltrace_test.go, eth/tracers/internal/tracetest/flat_calltrace_test.go, eth/tracers/internal/tracetest/prestate_test.go, eth/tracers/js/goja.go, eth/tracers/js/tracer_test.go, eth/tracers/live.go, eth/tracers/live/noop.go, eth/tracers/live/supply.go, eth/tracers/native/4byte.go, eth/tracers/native/call.go, eth/tracers/native/call2.go, eth/tracers/native/call_flat.go, eth/tracers/native/mux.go, eth/tracers/native/noop.go, eth/tracers/native/prestate.go
Reference PR: https://github.com/ethereum/go-ethereum/pull/30540
In this PR:
- Add missing `noop` live tracer.
- Move `ChainConfig` to tracers as a field instead of getting from `OnTxStart`.
- Rename `supply` struct to `supplyTracer`.
- Set default tracer config to empty obj.
=> core, eth/tracers: move chainconfig to tracers and some refactors

core/state_processor.go, core/state_processor_test.go, core/vm/interface.go, eth/state_accessor.go, eth/tracers/api.go, miner/worker.go, params/protocol_params.go
This PR implements spec https://eips.ethereum.org/EIPS/eip-2935 
Reference PR: https://github.com/ethereum/go-ethereum/pull/29465
=> all: implement EIP-2935

genesis/testnet.json, params/config.go, params/version.go
- Add testnet block to activate Kotaro hardfork
- Update ronin version to v1.0.3-unstable
=> genesis,params: config Kotaro hardfork testnet

core/txpool/blobpool/blobpool.go, core/txpool/blobpool/blobpool_test.go, core/txpool/legacypool/legacypool.go, core/txpool/legacypool/legacypool_test.go, core/txpool/reserver.go, core/txpool/subpool.go
This PR proposes a change to the authorizations' validation introduced
in commit [cdb66c8](https://github.com/ethereum/go-ethereum/commit/cdb66c89d6f8de3afd5e8d72bb5a0e3f46c27362). These changes make the expected behavior independent
of the order of admission of authorizations, improving the
predictability of the resulting state and the usability of the system
with it.
The current implementation behavior is dependent on the transaction
submission order: This issue is related to authorities and the sender of
a transaction, and can be reproduced respecting the normal nonce rules.
The issue can be reproduced by the two following cases:
**First case**
- Given an empty pool.
- Submit transaction `{ from: B, auths [ A ] }`: is accepted.
- Submit transaction `{ from: A }`: Is accepted: it …
=> core/txpool: allow tx and authority regardless of admission order

eth/tracers/api.go
Same issue with https://github.com/ethereum/go-ethereum/pull/29238
=> eth/tracers: fix concurrency issue when share blockCtx

core/blockchain_reader.go, eth/api.go, eth/api_backend.go, ethclient/ethclient.go, rpc/types.go, rpc/types_test.go
This PR introduces:
- The new "justified" block number support for the JSON-RPC API to allow clients to query the justified block
- Handle case nil finalized block causes panic in retrieving blob sidecar
=> core,eth,rpc: add justified block query, avoid crash if finalized block is nil
